name: Deploy to Proxmox VM

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
      
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
      
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.GHA_DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -H ${{ secrets.VM_IP }} > ~/.ssh/known_hosts

      - name: Deploy to Proxmox VM
        env:
          PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
          PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
          VM_IP: ${{ secrets.VM_IP }}
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sshpass -p ${{ secrets.PROXMOX_PASSWORD }} ssh -o StrictHostKeyChecking=no $PROXMOX_USERNAME@$VM_IP
