name: Deploy to Proxmox VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Proxmox VM
      env:
        PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
        PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
        PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
        VM_IP: ${{ secrets.VM_IP }}
        DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
      run: |
        sshpass -p "$PROXMOX_PASSWORD" ssh -o StrictHostKeyChecking=no $PROXMOX_USERNAME@$VM_IP << EOF
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          docker pull $DOCKER_IMAGE
          docker stop my-fastapi-app || true
          docker rm my-fastapi-app || true
          docker run -d --name my-fastapi-app -p 80:80 $DOCKER_IMAGE
        EOF
